// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGY6Fm2N6Lmk5xvwuTGFTgJ_RfzYAk8MI',
    appId: '1:251749379848:web:38a7291b2d05e1545e06bd',
    messagingSenderId: '251749379848',
    projectId: 'dummy-project-22d69',
    authDomain: 'dummy-project-22d69.firebaseapp.com',
    storageBucket: 'dummy-project-22d69.appspot.com',
    measurementId: 'G-GB0H2J5X9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1wzmfPyeeVLx-3r9bbD5JMOB-ShTcKEM',
    appId: '1:251749379848:android:0d6e37e5b979096e5e06bd',
    messagingSenderId: '251749379848',
    projectId: 'dummy-project-22d69',
    storageBucket: 'dummy-project-22d69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgpxKcG-_nLuPgwcUhp70Z4MVEE2j2WY4',
    appId: '1:251749379848:ios:38c25ffe2712f1a45e06bd',
    messagingSenderId: '251749379848',
    projectId: 'dummy-project-22d69',
    storageBucket: 'dummy-project-22d69.appspot.com',
    iosClientId: '251749379848-tmoj5hfknf31ovd2j41lbi2rk9gc7ucc.apps.googleusercontent.com',
    iosBundleId: 'dev.etornam.famliciousApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgpxKcG-_nLuPgwcUhp70Z4MVEE2j2WY4',
    appId: '1:251749379848:ios:38c25ffe2712f1a45e06bd',
    messagingSenderId: '251749379848',
    projectId: 'dummy-project-22d69',
    storageBucket: 'dummy-project-22d69.appspot.com',
    iosClientId: '251749379848-tmoj5hfknf31ovd2j41lbi2rk9gc7ucc.apps.googleusercontent.com',
    iosBundleId: 'dev.etornam.famliciousApp',
  );
}
